# Generated by Django 6.0.4 on 2026-04-26 00:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tecnicoasignado',
            name='unique_tecnico_proyecto',
        ),
        migrations.AlterUniqueTogether(
            name='tecnicoasignado',
            unique_together={('proyecto', 'tecnico')},
        ),
    ]
