# Generated by Django 6.0.4 on 2026-04-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_remove_tecnicoasignado_unique_tecnico_proyecto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('ver_proyectos', 'Ver lista de proyectos'), ('crear_proyecto', 'Crear proyecto'), ('editar_proyecto', 'Editar proyecto'), ('eliminar_proyecto', 'Archivar proyecto')], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
