# Generated by Django 6.0.4 on 2026-04-28 15:03

import apps.proyectos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_columnas_kanban'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='columnakanban',
            name='unique_columna_proyecto_slug',
        ),
        migrations.AlterField(
            model_name='actividad',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('en_revision', 'En revisión'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='comentarioactividad',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to=apps.proyectos.models._documento_upload, verbose_name='Archivo'),
        ),
        migrations.AlterUniqueTogether(
            name='columnakanban',
            unique_together={('proyecto', 'slug')},
        ),
    ]
