# Generated by Django 6.0.4 on 2026-04-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_remove_columnakanban_unique_columna_proyecto_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='grupo',
            field=models.CharField(blank=True, help_text='Agrupa actividades por épica o sub-fase', max_length=80, verbose_name='Épica / Grupo'),
        ),
    ]
