# Generated by Django 6.0.4 on 2026-04-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_configuracion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracion',
            options={'default_permissions': (), 'permissions': [('ver_configuracion', 'Ver configuración del sistema'), ('editar_configuracion', 'Editar configuración del sistema')], 'verbose_name': 'Configuración', 'verbose_name_plural': 'Configuración'},
        ),
    ]
