# Generated by Django 6.0.4 on 2026-04-24 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruc', models.CharField(max_length=11, unique=True, verbose_name='RUC')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, verbose_name='Nombre comercial')),
                ('direccion_fiscal', models.TextField(blank=True, verbose_name='Dirección fiscal')),
                ('sector', models.CharField(blank=True, max_length=100, verbose_name='Sector')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Contacto principal')),
                ('recibe_proforma', models.BooleanField(default=True, verbose_name='Recibe proformas')),
                ('recibe_informe', models.BooleanField(default=False, verbose_name='Recibe informes técnicos')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='clientes.empresa')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-es_principal', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='Postal Code')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('referencia', models.TextField(blank=True, verbose_name='Referencia')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Sede principal')),
                ('country', models.ForeignKey(default='PE', on_delete=django.db.models.deletion.PROTECT, to='location.country', verbose_name='Country')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='location.department', verbose_name='Department')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='location.district', verbose_name='District')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='clientes.empresa')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='location.province', verbose_name='Province')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['-es_principal', 'nombre'],
            },
        ),
    ]
