# Generated by Django 6.0.4 on 2026-04-25 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='direccion_fiscal',
        ),
        migrations.AddField(
            model_name='empresa',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='country',
            field=models.ForeignKey(default='PE', on_delete=django.db.models.deletion.PROTECT, to='location.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='location.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='location.district', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='location.province', verbose_name='Province'),
        ),
    ]
