# Generated by Django 6.0.4 on 2026-04-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_empresa_direccion_fiscal_empresa_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='sede',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
    ]
