# Generated by Django 6.0.4 on 2026-04-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_add_activo_to_sede_contacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'default_permissions': (), 'ordering': ['razon_social'], 'permissions': [('ver_clientes', 'Ver lista de clientes'), ('crear_cliente', 'Crear cliente'), ('editar_cliente', 'Editar cliente'), ('eliminar_cliente', 'Archivar cliente'), ('gestionar_contactos', 'Gestionar contactos y sedes')], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
    ]
