# Generated by Django 6.0.4 on 2026-04-25 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría de servicio',
                'verbose_name_plural': 'Categorías de servicio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CondicionComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('pago', 'Condiciones de pago'), ('viatico', 'Viáticos'), ('plazo', 'Plazo de entrega'), ('garantia', 'Garantía'), ('alcance', 'Alcance del servicio'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('es_default', models.BooleanField(default=False, verbose_name='Incluir por defecto en proformas')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Condición comercial',
                'verbose_name_plural': 'Condiciones comerciales',
                'ordering': ['orden', 'tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banco', models.CharField(choices=[('BCP', 'BCP'), ('BBVA', 'BBVA'), ('INTERBANK', 'Interbank'), ('SCOTIABANK', 'Scotiabank'), ('BN', 'Banco de la Nación'), ('BANBIF', 'BanBif'), ('OTRO', 'Otro')], max_length=20, verbose_name='Banco')),
                ('moneda', models.CharField(choices=[('PEN', 'Soles (S/)'), ('USD', 'Dólares ($)')], default='PEN', max_length=3, verbose_name='Moneda')),
                ('numero_cuenta', models.CharField(max_length=30, verbose_name='Número de cuenta')),
                ('cci', models.CharField(blank=True, max_length=30, verbose_name='CCI')),
                ('titular', models.CharField(max_length=200, verbose_name='Titular')),
                ('es_detraccion', models.BooleanField(default=False, verbose_name='Es cuenta de detracciones')),
                ('porcentaje_detraccion', models.DecimalField(blank=True, decimal_places=2, help_text='Solo si es cuenta de detracciones (Ej: 4.00)', max_digits=5, null=True, verbose_name='% Detracción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Cuenta bancaria',
                'verbose_name_plural': 'Cuentas bancarias',
                'ordering': ['banco', 'moneda'],
            },
        ),
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('compra', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Compra')),
                ('venta', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Tipo de cambio',
                'verbose_name_plural': 'Tipos de cambio',
                'ordering': ['-fecha'],
                'get_latest_by': 'fecha',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(blank=True, max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción técnica')),
                ('unidad', models.CharField(choices=[('servicio', 'Servicio'), ('hora', 'Hora'), ('punto', 'Punto'), ('mes', 'Mes'), ('dia', 'Día'), ('km', 'Kilómetro'), ('unidad', 'Unidad')], default='servicio', max_length=20, verbose_name='Unidad')),
                ('precio_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio (USD)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='catalogo.categoriaservicio', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['categoria__nombre', 'nombre'],
            },
        ),
    ]
