# Generated by Django 6.0.4 on 2026-04-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaservicio',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AddField(
            model_name='condicioncomercial',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
    ]
