# Generated by Django 6.0.4 on 2026-04-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_add_costo_to_catalogo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'default_permissions': (), 'ordering': ['categoria__nombre', 'nombre'], 'permissions': [('ver_catalogo', 'Ver catálogo'), ('gestionar_servicios', 'Gestionar servicios'), ('gestionar_productos', 'Gestionar productos'), ('gestionar_categorias', 'Gestionar categorías'), ('gestionar_condiciones', 'Gestionar condiciones comerciales'), ('gestionar_cuentas', 'Gestionar cuentas bancarias'), ('gestionar_tipos_cambio', 'Gestionar tipos de cambio y monedas')], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
    ]
