# Generated by Django 6.0.4 on 2026-04-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proformas', '0003_add_tecnico'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='proforma',
            name='unique_proforma_version',
        ),
        migrations.AlterField(
            model_name='proformaitem',
            name='unidad',
            field=models.CharField(choices=[('servicio', 'Servicio'), ('hora', 'Hora'), ('punto', 'Punto'), ('mes', 'Mes'), ('dia', 'Día'), ('km', 'Kilómetro'), ('unidad', 'Unidad'), ('par', 'Par'), ('rollo', 'Rollo'), ('metro', 'Metro'), ('kit', 'Kit'), ('caja', 'Caja'), ('licencia', 'Licencia'), ('global', 'Global')], default='servicio', max_length=20, verbose_name='Unidad'),
        ),
        migrations.AlterUniqueTogether(
            name='proforma',
            unique_together={('numero', 'version')},
        ),
    ]
