# Generated by Django 6.0.4 on 2026-04-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proformas', '0005_add_margen_costo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proforma',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('ver_proformas', 'Ver lista de proformas'), ('crear_proforma', 'Crear proforma'), ('editar_proforma', 'Editar proforma'), ('eliminar_proforma', 'Archivar proforma'), ('ver_costos', 'Ver costos internos y rentabilidad'), ('exportar_pdf', 'Exportar PDF de proforma')], 'verbose_name': 'Proforma', 'verbose_name_plural': 'Proformas'},
        ),
    ]
