# Generated by Django 6.0.4 on 2026-04-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_seed_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='color_badge',
            field=models.CharField(choices=[('bg-purple-100 text-purple-800', 'Violeta'), ('bg-blue-100 text-blue-800', 'Azul'), ('bg-green-100 text-green-800', 'Verde'), ('bg-yellow-100 text-yellow-800', 'Amarillo'), ('bg-red-100 text-red-800', 'Rojo'), ('bg-indigo-100 text-indigo-800', 'Índigo'), ('bg-pink-100 text-pink-800', 'Rosa'), ('bg-orange-100 text-orange-800', 'Naranja'), ('bg-gray-100 text-gray-800', 'Gris')], default='bg-gray-100 text-gray-800', max_length=80, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='es_superadmin',
            field=models.BooleanField(default=False, help_text='Omite todas las restricciones de permisos', verbose_name='Acceso total'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('tecnico', 'Técnico'), ('auditor', 'Auditor'), ('cliente', 'Cliente'), ('custom', 'Personalizado')], default='custom', help_text='Determina el conjunto de permisos iniciales y qué usuarios aparecen como técnicos', max_length=20, verbose_name='Tipo base'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
