# Generated by Django 6.0.4 on 2026-04-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0004_alter_rol_color_badge_alter_rol_es_superadmin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'default_permissions': (), 'ordering': ['nombre'], 'permissions': [('ver_usuarios', 'Ver lista de usuarios'), ('gestionar_usuarios', 'Gestionar usuarios'), ('gestionar_roles', 'Gestionar roles y permisos')], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(blank=True, related_name='roles', to='auth.permission', verbose_name='Permisos'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('tecnico', 'Técnico'), ('auditor', 'Auditor'), ('cliente', 'Cliente'), ('custom', 'Personalizado')], default='custom', help_text='Tipo de rol para clasificación', max_length=20, verbose_name='Tipo base'),
        ),
        migrations.DeleteModel(
            name='PermisoModulo',
        ),
    ]
