# Generated by Django 6.0.4 on 2026-04-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantilladocumento',
            options={'default_permissions': (), 'ordering': ['tipo', 'nombre'], 'permissions': [('ver_documentos', 'Ver documentos generados'), ('crear_documento', 'Crear documento'), ('editar_documento', 'Editar documento'), ('eliminar_documento', 'Archivar documento'), ('gestionar_plantillas', 'Gestionar plantillas de documentos')], 'verbose_name': 'Plantilla de documento', 'verbose_name_plural': 'Plantillas de documentos'},
        ),
    ]
